import { Inter } from "next/font/google";
import "./globals.css";
// import Main from "../components/Main"; // Ensure Main is a client component
// import NewMain from "../components/NewMain";
import "../styles/common.css";
import "../styles/App.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TORSO for MEN ",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        {/* <NewMain /> */}
        {/* <Main /> Main should be within body */}
        {children}
      </body>
    </html>
  );
}
